[package]
name = "icn_node"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
ed25519-dalek = "1.0"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9"
tokio = { version = "1.0", features = ["full"] }
bytes = "1.0"
hex = "0.4"


[dev-dependencies]
tokio-test = "0.4"