[package]
name = "cooperative-blockchain"
version = "0.2.7"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
ed25519-dalek = "1.0"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9"